name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - run: zig build ci --summary all
      - name: getversion
        id: version
        run: echo "version=$(cat zig-out/version-release)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: anyzig-${{ steps.version.outputs.version }}-archives
          path: |
            zig-out/anyzig-aarch64-linux.tar.gz
            zig-out/anyzig-aarch64-macos.tar.gz
            zig-out/anyzig-aarch64-windows.zip
            zig-out/anyzig-arm-linux.tar.gz
            zig-out/anyzig-powerpc64le-linux.tar.gz
            zig-out/anyzig-riscv64-linux.tar.gz
            zig-out/anyzig-s390x-linux.tar.gz
            zig-out/anyzig-x86-linux.tar.gz
            zig-out/anyzig-x86-windows.zip
            zig-out/anyzig-x86_64-linux.tar.gz
            zig-out/anyzig-x86_64-macos.tar.gz
            zig-out/anyzig-x86_64-windows.zip
    outputs:
      version: ${{ steps.version.outputs.version }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: anyzig-*-archives
          merge-multiple: true
          path: artifacts
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "anyzig ${{ github.ref_name }}" \
            --generate-notes \
            artifacts/*
